### ISSUE TITLE
Give coins or my dad will ban you!!

### ISSUE THREAD

**Issue by felda** [hira-io/buttcoin-miner#1]
┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪ EVERYONE GET IN HERE ♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪♫ ┌༼ຈل͜ຈ༽┘ ♪

**Comment by Polsaker** [comment]
Too late, I already banned your dad
